workflow:
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - when: always

variables:
  DOCKER_REGISTRY: wearestancer
  PYTHON_VERSION: "3.10"

Create archive:
  stage: deploy

  image: ${DOCKER_REGISTRY}/python:${PYTHON_VERSION}

  before_script:
    - python3 --version
    - pipenv --version
    - pipenv install
    - pipenv requirements > ./requirements.txt

  script:
    - pipenv run create-archive

  artifacts:
    paths:
      - '*.zip'

Ruff format:
  image: ${DOCKER_REGISTRY}/python:${PYTHON_VERSION}

  stage: test

  before_script:
    - mkdir -p "$PIP_CACHE_DIR" "$PIPENV_CACHE_DIR"

    - python --version
    - pipenv --version
    - pipenv install --dev

  script:
    - pipenv run ruff format --diff

  cache:
    key: $CI_COMMIT_BRANCH
    paths:
      - $CACHE_DIR

    when: always

  variables:
    TMP_CACHE_DIR: .cache
    CACHE_DIR: "${CI_PROJECT_DIR}/${TMP_CACHE_DIR}"
    CACHE_FALLBACK_KEY: "$CI_DEFAULT_BRANCH"
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/${TMP_CACHE_DIR}/pip"
    PIPENV_CACHE_DIR: "${CI_PROJECT_DIR}/${TMP_CACHE_DIR}/pipenv"
