workflow:
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - when: always


.base:
  image: ${DOCKER_REGISTRY}/python:3.10-pipenv

  before_script:
    - mkdir -p "$PIP_CACHE_DIR" "$PIPENV_CACHE_DIR"

    - python --version
    - pipenv --version

  variables:
    DOCKER_REGISTRY: wearestancer

    TMP_CACHE_DIR: .cache
    CACHE_DIR: "${CI_PROJECT_DIR}/${TMP_CACHE_DIR}"
    CACHE_FALLBACK_KEY: "$CI_DEFAULT_BRANCH"
    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/${TMP_CACHE_DIR}/pip"
    PIPENV_CACHE_DIR: "${CI_PROJECT_DIR}/${TMP_CACHE_DIR}/pipenv"


Create archive:
  extends:
    - .base

  stage: deploy

  script:
    - pipenv requirements > ./requirements.txt
    - pipenv run create-archive

  artifacts:
    paths:
      - '*.zip'


Ruff format:
  extends:
    - .base

  stage: test

  script:
    - pipenv install --dev
    - pipenv run ruff format --diff

  cache:
    key: $CI_COMMIT_BRANCH
    paths:
      - $CACHE_DIR

    when: always
